export const LOAD_CONF_SUCCESS = 'LOAD_CONF_SUCCESS';  

export const EDIT_CONF_SUCCESS = 'EDIT_CONF_SUCCESS';

export const LOAD_WORKERS_SUCCESS = 'LOAD_WORKERS_SUCCESS';

export const EDIT_WORKER_SUCCESS = 'EDIT_WORKER_SUCCESS';

export const ADD_WORKER_SUCCESS = 'ADD_WORKER_SUCCESS';

export const DELETE_WORKER_SUCCESS = 'DELETE_WORKER_SUCCESS';

export const ADD_COMPENSATION_BY_WORKER ='ADD_COMPENSATION_BY_WORKER';

export const LOAD_COMPENSATIONS_SUCCESS= 'LOAD_COMPENSATIONS_SUCCESS';

export const LOAD_ON_CALL_WORKERS_SUCCESS = 'LOAD_ON_CALL_WORKERS_SUCCESS';

export const ADD_TO_ON_CALL_WORKER_SUCCESS = 'ADD_TO_ON_CALL_WORKER_SUCCESS';

export const REMOVE_FROM_ON_CALL_WORKER_SUCCESS = 'REMOVE_FROM_ON_CALL_WORKER_SUCCESS';
